# Generated by Django 6.0.2 on 2026-02-10 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('img_url', models.TextField(blank=True, max_length=2048)),
                ('posted_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
