# Generated by Django 6.0.2 on 2026-02-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
            ],
        ),
    ]
