# Generated by Django 6.0 on 2026-02-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot_site', '0003_signupdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindata',
            name='dob',
        ),
        migrations.AddField(
            model_name='signupdata',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='signupdata',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
